# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693a42d2679b73744b35667d95669851fd8718600bbe1a7985a85518c80f7dd51b81f145e2b62fe199f6461039baba3aaeb74e810b29aea2a5bc16a79328898c

test:
  secret_key_base: 96993db4e9e5d7974841fde2a8b6c56842536766b184a3df6a3f498417f129d00a17185cac23873cc8f9e8e405166315cacc9a3df304ee63de5f2d7107e19038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
